# Generated by Django 3.0.5 on 2020-04-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_auto_20200416_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='host',
            new_name='user',
        ),
    ]
